version: '3.9'

services:
  caddy:
    pull_policy: build
    build: .
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
      - "${HTTPS_PORT}:443/udp"
    volumes:
      - ${FS_DIR}:/fs
      - ${APPDATA_DIR}:/data
      - ${CONFIG_DIR}:/config
    restart: always
